website:
  container_name: website
  build: .
  ports:
    - 80:80
    - 443:443
    - 4567:4567
  links:
    - sinatra_app
sinatra_app:
  container_name: sinatra_app
  build: ./sinatra-app/
  ports:
    - 5000:4567
